baseURL: "https://guildflow.com/"
languageCode: "en-us"
title: "Guildflow"

theme: "guildflow-theme"
params:
  author: Mike Zornek
  description: Guildflow allows meetup organizers to create a modern group website that respects the data and privacy rights of its members.
  mainCtaTitle: "Create Group"
  mainCtaUrl: https://clubhouse.host/create-group
menu:
  main:
    - name: Features
      url: /features/
      weight: 10
    - name: Pricing
      url: /pricing/
      weight: 20
    - name: Blog
      url: /blog/
      weight: 40
    - name: FAQ
      url: /faq/
      weight: 50
    - name: Contact
      url: /contact/
      weight: 60
markup:
  goldmark:
    renderer:
      unsafe: true
